version: '3.8'

services:
  # GitHub Actions Runner with Claude Code
  gha-runner:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GO_VERSION=1.25.0
        - NODE_VERSION=20
        - PYTHON_VERSION=3.11
        - OTEL_VERSION=0.93.0
    image: zeeke-ai-runner:latest
    container_name: zeeke-ai-runner

    # Run as claude user
    user: claude

    # Environment variables
    environment:
      # GitHub
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_REPOSITORY=${GITHUB_REPOSITORY:-dahendel/zeeke-ai}
      - GITHUB_WORKSPACE=/home/claude/workspace

      # Anthropic
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}

      # Git configuration
      - GIT_USER_NAME=${GIT_USER_NAME:-Claude Code Runner}
      - GIT_USER_EMAIL=${GIT_USER_EMAIL:-claude@zeeke-ai.local}

      # Runner configuration
      - RUN_PREFLIGHT=${RUN_PREFLIGHT:-true}
      - RUNNER_ALLOW_RUNASROOT=0

      # Skill Seekers path (if mounted)
      - SKILL_SEEKERS_PATH=${SKILL_SEEKERS_PATH:-/mcp/skill-seekers}

      # Go configuration
      - GOPATH=/go
      - GOBIN=/go/bin
      - GO111MODULE=on
      - CGO_ENABLED=0

      # Python configuration
      - PYTHONUNBUFFERED=1
      - PIP_NO_CACHE_DIR=1

      # Observability configuration
      - ENABLE_OTEL=${ENABLE_OTEL:-true}
      - OTEL_ENDPOINT=${OTEL_ENDPOINT:-}
      - OTEL_INSECURE=${OTEL_INSECURE:-false}
      - OTEL_CA_FILE=${OTEL_CA_FILE:-}
      - OTEL_CERT_FILE=${OTEL_CERT_FILE:-}
      - OTEL_KEY_FILE=${OTEL_KEY_FILE:-}
      - OTEL_AUTH_HEADER=${OTEL_AUTH_HEADER:-}
      - OTEL_LOG_LEVEL=${OTEL_LOG_LEVEL:-info}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - USE_JSON_LOGS=${USE_JSON_LOGS:-true}
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - SERVICE_VERSION=${SERVICE_VERSION:-1.0.0}

    # Volumes
    volumes:
      # Mount project workspace (read/write)
      - ./:/home/claude/workspace:rw

      # Mount Go cache for faster builds
      - go-cache:/go/pkg/mod
      - go-build-cache:/home/claude/.cache/go-build

      # Mount Docker socket for act (if needed)
      - /var/run/docker.sock:/var/run/docker.sock

      # Mount user-level agents (read-only)
      - ${HOME}/.claude/agents:/home/claude/.claude/agents:ro

      # Mount Skill_Seekers MCP server (if available, read-only)
      - ${SKILL_SEEKERS_PATH:-./mcp/skill-seekers}:/mcp/skill-seekers:ro

      # Mount secrets file (read-only)
      - ./.secrets:/home/claude/.secrets:ro

    # Ports
    ports:
      # Expose Prometheus metrics endpoint
      - "8889:8889"

    # Working directory
    working_dir: /home/claude/workspace

    # Command (interactive shell by default)
    command: bash

    # Keep container running
    stdin_open: true
    tty: true

    # Network
    network_mode: bridge

    # Resource limits (adjust as needed)
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8G
        reservations:
          cpus: '2'
          memory: 4G

    # Restart policy
    restart: unless-stopped

    # Health check using observability script
    healthcheck:
      test: ["/usr/local/bin/health-check", "ready"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

    # Logging configuration with rotation
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "service,environment"
        env: "ENVIRONMENT,SERVICE_VERSION"

  # Optional: act runner for workflow testing
  act-runner:
    image: zeeke-ai-runner:latest
    container_name: zeeke-ai-act-runner
    user: claude

    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - ENABLE_OTEL=false  # Disable OTEL for act runner
      - LOG_LEVEL=INFO

    volumes:
      - ./:/home/claude/workspace:rw
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.secrets:/home/claude/.secrets:ro
      - act-cache:/home/claude/.cache/act

    working_dir: /home/claude/workspace

    # Run act by default
    command: act -l

    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    profiles:
      - testing

# Volumes
volumes:
  go-cache:
    driver: local
  go-build-cache:
    driver: local
  act-cache:
    driver: local

# Networks
networks:
  default:
    driver: bridge
